version: 2
jobs:
  build:
    machine:
      enabled: true
    steps:
      - run: make ubercalc
  test:
    machine:
      enabled: true
    steps:
      - run: make dtest
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test

