version: 2
jobs:
  test:
    machine: true
    steps:
      - checkout
      - run: sudo apt-get install -y cl-launch
      - run: make dtest
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
