version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: make docker
  test:
    machine: true
    steps:
      - checkout
      - run: make dtest
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test

